project:
  type: website

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: about.qmd
      - publications.qmd
      - teaching.qmd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

