baseurl: https://ldmnch.github.io/layitx/
title: Hello!
theme: hugo-creative-portfolio-theme
publishDir: "docs"
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: '&copy;2016 UBA | UNSAM | EcoFeminita'
  description: Describe your website
  email: laiadomenechburin@gmail.com
  navlinks:
    - home: yes
      name: Home
      url: portfolio/
    - name: About
      url: about/
  sidebarAbout:
    - My name is Laia Domenech Burin. 
    - I'm finishing my Sociology Licenciate degree at University of Buenos Aires, so I'm an almost social data scientist. 
    - My main interest is applied data science for inequalities, gender studies and spatial analysis.
    - Here are some of the projects I've worked on.
  social:
    email: laiadomenechburin@gmail.com.com
    github: https://github.com/ldmnch/
    linkedin: https://www.linkedin.com/in/laia-domenech-burin-176b6017a/
    twitter: https://twitter.com/layitx
  style: default
